[package]
name = "myrcontroller"
version = "0.1.0"
authors = ["tsathish <tsatiz@gmail.com>"]

[dependencies]
serialport = "2.3"
hex = "0.3"
ihex = "1.0"
enum_primitive = "0.1"
num = "0.1"
crc16 = "0.3.4"
rust-ini = "0.10"
diesel = { version = "1.2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "1.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"