[package]
name = "myscontroller-rs"
version = "0.4.2"
authors = ["tsathish <tsatiz@gmail.com>"]

[dependencies]
serialport = "2.3"
hex = "0.3"
ihex = "1.0"
enum_primitive = "0.1"
num = "0.1"
crc16 = "0.3.4"
rust-ini = "0.10"
diesel = { version = "1.2.0", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = "1.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
rocket = {git = "https://github.com/SergioBenitez/Rocket.git"}
rocket_codegen = {git = "https://github.com/SergioBenitez/Rocket.git"}
r2d2 = "0.8.2"
rocket_contrib = {git = "https://github.com/SergioBenitez/Rocket.git"}
crossbeam-channel = "0.1"
multipart = "0.14.2"

[package.metadata.deb]
maintainer = "Sathishkumar <tsatiz@gmail.com>"
extended-description = """\
A proxy server for MySController \
to perform the ota updates."""
depends = "$auto"
section = "rust"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/myscontroller-rs", "/usr/local/bin/myscontroller-rs", "755"],
    ["conf.ini", "/etc/myscontroller-rs/conf.ini", "644"],
    ["service/systemd/myscontroller-rs.service", "/etc/systemd/system/myscontroller-rs.service", "644"],
]
conf-files = [
  "/etc/myscontroller-rs/conf.ini",
  "/etc/systemd/system/myscontroller-rs.service"
]
